/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ballbert.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ballbert.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="lid" position={[2.478, 26.747, 1.049]} rotation={[-Math.PI, 0, 0]} scale={0.164}>
          <mesh name="lid_1" geometry={nodes.lid_1.geometry} material={materials['Material.001']} />
          <mesh name="lid_2" geometry={nodes.lid_2.geometry} material={materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ballbert.glb')
