import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 >Ballbert Voice Assistant</h1>
        <div className={styles.image}>
          <Image src="/ballbertFront.png" alt="Picture of the author" fill />
        </div>
      </main>
      <footer>
        <div className="links">
          <a href={"https://github.com/seesi8/Ballbert_Ios_App/blob/main/privacy_policy"}>Privacy Policy </a>
          <a href={"mailto:sbliebert@ballbert.com"}>Contact Email</a>
        </div>
        <p>© 2023, Ballbert, LLC</p>
      </footer>
    </>
  );
}
